use_eeg: True

Training1_trials_congruent_strong: 0
Training1_trials_congruent_weak: 0
Training1_trials_incongruent_strong: 0
Training1_trials_incongruent_strong_2: 0
Training1_trials_incongruent_weak: 0
Training1_trials_neutral: 8
Training1_trials_neutral_2: 8

Training2_trials_congruent_strong: 8
Training2_trials_congruent_weak: 0
Training2_trials_incongruent_strong: 4
Training2_trials_incongruent_strong_2: 4
Training2_trials_incongruent_weak: 0
Training2_trials_neutral: 4
Training2_trials_neutral_2: 4

Training_Resp_time: 4
Training_Wait_time: 1

Number_of_blocks: 1
Experiment_trials_congruent_strong: 100
Experiment_trials_congruent_weak: 0
Experiment_trials_incongruent_strong: 50
Experiment_trials_incongruent_strong_2: 50
Experiment_trials_incongruent_weak: 0
Experiment_trials_neutral: 50
Experiment_trials_neutral_2: 50

Experiment_Resp_time: 3
Experiment_Wait_time: 1

Jitter: 1

Fix_time: 1
Feedb: True
Feedb_time: 1

words_dist: 40
